..

diff --git a/nightlcd b/nightlcd
--- a/nightlcd
+++ b/nightlcd
@@ -9,14 +9,14 @@ C_HOUR=$(date "+%H")
 
 checkRequirements() {
 
-        requirements=( 'redshift' )
+		requirements=( 'redshift' )
 
-        for requirement in "${requirements[@]}"; do
-                if ! command -v "$requirement" > /dev/null; then
-                        echo -e "\n${rc}${rc}$requirement not found!$rc"
-                        exit 1
-                fi
-        done
+		for requirement in "${requirements[@]}"; do
+				if ! command -v "$requirement" > /dev/null; then
+						echo -e "\n${rc}${rc}$requirement not found!$rc"
+						exit 1
+				fi
+		done
 
 }
 
@@ -39,15 +39,15 @@ setWarm(){
 
 isItNight(){
 
-        if [[ "${C_HOUR}" -ge "${NIGHT_TIME}" ]]; then
-                echo "🌃 It's night time, setting LCD color to warm..."
+		if [[ "${C_HOUR}" -ge "${NIGHT_TIME}" ]]; then
+				echo "🌃 It's night time, setting LCD color to warm..."
 				return 1
-        elif [[ "${C_HOUR}" -lt "${NIGHT_TIME}" ]]; then
-                echo "🌇 It's day time, setting LCD color to cold..."
+		elif [[ "${C_HOUR}" -lt "${NIGHT_TIME}" ]]; then
+				echo "🌇 It's day time, setting LCD color to cold..."
 				return 0
-        else
-                exit 1
-        fi
+		else
+				exit 1
+		fi
 
 }
 
diff --git a/ocr b/ocr
--- a/ocr
+++ b/ocr
@@ -7,8 +7,8 @@ REQUIREMENTS=( 'tesseract' 'xfce4-screenshooter' 'xclip' 'notify-send' )
 
 for REQ in "${REQUIREMENTS[@]}"; do
   if ! command -v "${REQ}" >/dev/null 2>&1; then
-    echo "${REQ} not found!"
-    exit 1
+	echo "${REQ} not found!"
+	exit 1
   fi
 done
 
