shfmt

diff --git a/nightlcd b/nightlcd
--- a/nightlcd
+++ b/nightlcd
@@ -1,33 +1,29 @@
 #!/bin/bash
 set -euxo pipefail
 
-
-
 NIGHT_TIME='22'
 C_HOUR=$(date "+%H")
 
-
 checkRequirements() {
 
-		requirements=( 'redshift' )
+	requirements=('redshift')
 
-		for requirement in "${requirements[@]}"; do
-				if ! command -v "$requirement" > /dev/null; then
-						echo -e "\n${rc}${rc}$requirement not found!$rc"
-						exit 1
-				fi
-		done
+	for requirement in "${requirements[@]}"; do
+		if ! command -v "$requirement" >/dev/null; then
+			echo -e "\n${rc}${rc}$requirement not found!$rc"
+			exit 1
+		fi
+	done
 
 }
 
-
-setCold(){
+setCold() {
 
 	redshift -x
 
 }
 
-setWarm(){
+setWarm() {
 
 	TEMP='3500'
 
@@ -36,18 +32,17 @@ setWarm(){
 
 }
 
+isItNight() {
 
-isItNight(){
-
-		if [[ "${C_HOUR}" -ge "${NIGHT_TIME}" ]]; then
-				echo "🌃 It's night time, setting LCD color to warm..."
-				return 1
-		elif [[ "${C_HOUR}" -lt "${NIGHT_TIME}" ]]; then
-				echo "🌇 It's day time, setting LCD color to cold..."
-				return 0
-		else
-				exit 1
-		fi
+	if [[ ${C_HOUR} -ge ${NIGHT_TIME} ]]; then
+		echo "🌃 It's night time, setting LCD color to warm..."
+		return 1
+	elif [[ ${C_HOUR} -lt ${NIGHT_TIME} ]]; then
+		echo "🌇 It's day time, setting LCD color to cold..."
+		return 0
+	else
+		exit 1
+	fi
 
 }
 
diff --git a/ocr b/ocr
--- a/ocr
+++ b/ocr
@@ -1,37 +1,40 @@
 #!/bin/bash
 # Optical Character Recognition.
 
-[[ -z ${XAUTHORITY} ]] && { echo "Can't find X display to contact!"; exit 1; }
+[[ -z ${XAUTHORITY} ]] && {
+	echo "Can't find X display to contact!"
+	exit 1
+}
 
-REQUIREMENTS=( 'tesseract' 'xfce4-screenshooter' 'xclip' 'notify-send' )
+REQUIREMENTS=('tesseract' 'xfce4-screenshooter' 'xclip' 'notify-send')
 
 for REQ in "${REQUIREMENTS[@]}"; do
-  if ! command -v "${REQ}" >/dev/null 2>&1; then
-	echo "${REQ} not found!"
-	exit 1
-  fi
+	if ! command -v "${REQ}" >/dev/null 2>&1; then
+		echo "${REQ} not found!"
+		exit 1
+	fi
 done
 
 COMPOSITOR='picom'
 COMPOSITOR_PID=$(pidof "${COMPOSITOR}")
 
-if [[ -n "${COMPOSITOR_PID}" ]]; then
-  echo "Killing compositor to prevent blur during screenshot..."
-  kill "${COMPOSITOR_PID}"
-  COMPOSITOR_WAS_RUNNING='0'
+if [[ -n ${COMPOSITOR_PID} ]]; then
+	echo "Killing compositor to prevent blur during screenshot..."
+	kill "${COMPOSITOR_PID}"
+	COMPOSITOR_WAS_RUNNING='0'
 fi
 
 SCREENSHOT_OUTFILE="/tmp/screenshot_${RANDOM}"
 xfce4-screenshooter -r -s "${SCREENSHOT_OUTFILE}"
 
-[[ "${COMPOSITOR_WAS_RUNNING}" -eq '0' ]] && "${COMPOSITOR}" &
-[[ ! -e "${SCREENSHOT_OUTFILE}" ]] && exit 1
+[[ ${COMPOSITOR_WAS_RUNNING} -eq '0' ]] && "${COMPOSITOR}" &
+[[ ! -e ${SCREENSHOT_OUTFILE} ]] && exit 1
 
 OCR_OUTPUT="/tmp/ocr_${RANDOM}"
 tesseract "${SCREENSHOT_OUTFILE}" "${OCR_OUTPUT}" || exit 1
 
 OCR_TEXT=$(<"${OCR_OUTPUT}.txt")
-[[ -z "${OCR_TEXT}" ]] && exit 1
+[[ -z ${OCR_TEXT} ]] && exit 1
 
 APPNAME="${0}"
 notify-send -a "${APPNAME}" "${OCR_TEXT}$(echo -e '\n\n📋 String copied to clipboard!')"
diff --git a/otomate b/otomate
--- a/otomate
+++ b/otomate
@@ -8,9 +8,8 @@ bold='\e[1m'
 ul='\e[4m'
 rc='\e[0m'
 
-
 showBanner() {
-echo -e "$bc
+	echo -e "$bc
 
 
 			   d8P									 d8P
@@ -27,10 +26,10 @@ echo -e "$bc
 checkRequirements() {
 
 	crawler='waybackurls'
-	requirements=( "$crawler" 'subfinder' 'sqlmap' 'curl' 'wpscan' 'nuclei' )
+	requirements=("$crawler" 'subfinder' 'sqlmap' 'curl' 'wpscan' 'nuclei')
 
 	for requirement in "${requirements[@]}"; do
-		if ! command -v "$requirement" > /dev/null; then
+		if ! command -v "$requirement" >/dev/null; then
 			echo -e "\n$warn ! ${rc}${rc}$requirement not found!$rc"
 			exit 1
 		fi
@@ -51,7 +50,7 @@ checkIsUp() {
 
 wpscanUrl() {
 
-	url=$( echo "$url" | cut -d '/' -f 3 | sort -u )
+	url=$(echo "$url" | cut -d '/' -f 3 | sort -u)
 	echo -e "\n$ok + $rc$ul$bold$url$rc seems to run wordpress, running wpscan...$rc"
 
 	wpscan_cmd='wpscan --random-user-agent -e vp, vt, cd, dbe, u, m --stealthy --ignore-main-redirect'
@@ -68,15 +67,14 @@ sqlmapUrl() {
 	echo -e "\n$info → ${rc}Searching for SQLi on $ul$bold$url$rc...$rc"
 
 	$sqlmap_cmd
-#	$sqlmap_cmd --forms
+	#	$sqlmap_cmd --forms
 
 }
-
 
 searchSubdomain() {
 
 	echo -e "\n$info → ${rc}Searching for subdomain on $ul$bold$target$rc...$rc"
-	found_subdomains=( $( subfinder -d "$target" -all -silent ) )
+	found_subdomains=($(subfinder -d "$target" -all -silent))
 
 	if [ -z "$found_subdomains" ]; then
 		echo -e "\n$warn ! ${rc}${rc}No subdomain found on $ul$bold$target$rc!$rc"
@@ -90,13 +88,12 @@ searchSubdomain() {
 
 }
 
-
 searchUrl() {
 
 	echo -e "\n$info → ${rc}Searching for URL on $ul$bold$subdomain$rc...$rc"
-#	found_urls=( $( katana -aff -jc -kf -fx -retry 3 -u "$subdomain" -silent ) )
-#	found_urls=( $( $crawler $subdomain ))
-	found_urls=( $( $crawler $subdomain | sort -u ))
+	#	found_urls=( $( katana -aff -jc -kf -fx -retry 3 -u "$subdomain" -silent ) )
+	#	found_urls=( $( $crawler $subdomain ))
+	found_urls=($($crawler $subdomain | sort -u))
 
 	if [ -z "$found_urls" ]; then
 		echo -e "\n$warn ! ${rc}${rc}No URL found on $ul$bold$subdomain$rc!$rc"
@@ -119,21 +116,20 @@ testTarget() {
 
 		for url in "${found_urls[@]}"; do
 
-			if echo "$url" | grep '/wp-' 1>/dev/null; then wpscanUrl ; fi
+			if echo "$url" | grep '/wp-' 1>/dev/null; then wpscanUrl; fi
 
-			if echo -e "\n$url" | grep -aE '=|\?' 1>/dev/null ; then sqlmapUrl; fi
+			if echo -e "\n$url" | grep -aE '=|\?' 1>/dev/null; then sqlmapUrl; fi
 
 		done
 
 	done
 }
 
-
 main() {
 
 	checkRequirements
 
-	targets=( "$@" )
+	targets=("$@")
 
 	if [ -z $targets ]; then
 
@@ -141,7 +137,6 @@ main() {
 		exit 1
 
 	fi
-
 
 	for target in "${targets[@]}"; do
 
@@ -154,4 +149,4 @@ main() {
 
 }
 
-showBanner&&main "$@"
+showBanner && main "$@"
diff --git a/start-live-vm b/start-live-vm
--- a/start-live-vm
+++ b/start-live-vm
@@ -2,7 +2,6 @@
 
 RC='\e[0m' WARN='\e[31m' GOOD='\e[32m'
 
-
 printUsage() {
 
 	echo -e "${WARN}Usage:\n\n.${0} <disk image>${RC}"
@@ -10,14 +9,14 @@ printUsage() {
 
 }
 
-[[ -z "${#}" || ! -e "${1}" ]] && printUsage || ISO="${1}"
+[[ -z ${#} || ! -e ${1} ]] && printUsage || ISO="${1}"
 
 checkReq() {
 
-	ARCH=$( uname -m ) REQS=( "qemu-system-${ARCH}" )
+	ARCH=$(uname -m) REQS=("qemu-system-${ARCH}")
 
 	for REQ in "${REQS[@]}"; do
-		if ! command -v "${REQ}">/dev/null;then
+		if ! command -v "${REQ}" >/dev/null; then
 			echo -e "To run me, you need:${WARN}${REQ}${RC}"
 			exit 1
 		fi
@@ -25,8 +24,11 @@ checkReq() {
 
 }
 
-checkFailed() {	echo -ne "${WARN}[FAILED]${RC}\n"; exit 1; }
-checkPassed() {	echo -ne "${GOOD}[OK]${RC}\n"; }
+checkFailed() {
+	echo -ne "${WARN}[FAILED]${RC}\n"
+	exit 1
+}
+checkPassed() { echo -ne "${GOOD}[OK]${RC}\n"; }
 
 echo -ne "Verifying system requirements...${RC}"
 if checkReq; then
@@ -36,14 +38,14 @@ else
 fi
 
 echo -ne "Checking CPU virtualization capability...${RC}"
-if grep -Ewo 'vmx|svm' /proc/cpuinfo>/dev/null; then
+if grep -Ewo 'vmx|svm' /proc/cpuinfo >/dev/null; then
 	checkPassed
 else
 	checkFailed
 fi
 
 echo -ne "Computing available RAM...${RC}"
-if AVAIL_MEM=$(( $(grep -i MemAvail /proc/meminfo | awk '{print $2}') / 1024 )); then
+if AVAIL_MEM=$(($(grep -i MemAvail /proc/meminfo | awk '{print $2}') / 1024)); then
 	checkPassed
 else
 	checkFailed
