add files

diff --git a/randombg b/randombg
--- a/randombg
+++ b/randombg
@@ -1,10 +1,64 @@
 #!/bin/bash
 set -euo pipefail
 
-IMG_PATH="/usr/share/backgrounds/gnome/"
-FILE_TYPE='.png|.jpg|.jpeg'
 
-RANDOM_BG=$( find -L "${IMG_PATH}" | grep -E "${FILE_TYPE}"|shuf|head -n1 )
+NIGHT_TIME='22'
+C_HOUR=$(date "+%H")
 
-#feh --no-xinerama --bg-fill "${RANDOM_BG}" ## span accross multiple screens
-feh --bg-fill "${RANDOM_BG}"
+isItNight(){
+
+	if [[ "${C_HOUR}" -ge "${NIGHT_TIME}" ]]; then
+		W_TYPE='\-d'
+		echo "🌃 It's night time, searching for a dark background..."
+	elif [[ "${C_HOUR}" -lt "${NIGHT_TIME}" ]]; then
+		W_TYPE='\-l'
+		echo "🌇 It's day time, searching for a light background..."
+	else
+		exit 1
+	fi
+
+}
+
+findBackground(){
+
+	IMG_PATH='/usr/share/backgrounds/gnome/'
+
+	if [ ! -d "${IMG_PATH}" ]; then
+		echo "${IMG_PATH} not found!"
+		exit 1
+	fi
+
+	FILE_TYPE='.svg|.png|.jpg|.jpeg'
+
+	RANDOM_BG=$(
+		find -O3 -L "${IMG_PATH}" \
+			| grep -E "${FILE_TYPE}" \
+			| shuf \
+			| grep "${W_TYPE}" \
+			| head -n1
+	)
+
+}
+
+
+setBackground(){
+
+	#feh --no-xinerama --bg-fill "${RANDOM_BG}" ## span accross multiple screens
+	feh --bg-fill "${RANDOM_BG}"
+
+}
+
+main(){
+
+	if isItNight; then
+		if findBackground; then
+			if setBackground; then
+				exit 0
+			fi
+
+		fi
+	fi
+
+}
+
+main
