add check

diff --git a/start-live-vm b/start-live-vm
--- a/start-live-vm
+++ b/start-live-vm
@@ -1,19 +1,40 @@
 #!/bin/bash
-RC='\e[0m';RED='\e[31m';GREEN='\e[32m'
-ISO="${1}"
-MEM="${2:-1024}"
-REQ='qemu-system-x86_64'
-MEM_AVAIL=$(( $(grep -i MemAvail /proc/meminfo | awk '{print $2}') / 1024 ))
 
-[[ ! ${ISO} || ! -e ${ISO} ]]&&{ echo -e "Start a live VM with qemu.\n\nUsage:./start-live-vm <ISO> <RAM(MB)>";exit 1; }
-[[ ${MEM} -gt ${MEM_AVAIL} ]]&&{ echo -e "${RED}You don't have enough RAM! (${MEM_AVAIL}MB available right now)${RC}";exit 1; }
+RC='\e[0m' WARN='\e[31m' GOOD='\e[32m'
 
-if ! which ${REQ}>/dev/null;then
-	echo -e "To run me, you need:${RED}${REQ}${RC}"
-	exit 1
+[[ -z "${#}" ]] && { echo -e "${WARN}Usage:\n\n./${0} <disk image>${RC}";exit 1; } || ISO="${1}"
+
+ARCH=$( uname -m ) REQS=( "qemu-system-${ARCH}" )
+
+echo -ne "Checking CPU virtualization capability...${RC}"
+if grep -Ewo 'vmx|svm' /proc/cpuinfo>/dev/null; then
+	echo -ne "${GOOD}[OK]${RC}\n"
+else
+	echo -ne "${WARN}[FALSE]${RC}\n"
 fi
 
-if ! echo -ne "${GREEN}Starting ${ISO}...${RC}"|qemu-system-x86_64 -boot d -cdrom ${ISO} -m ${MEM};then
-	echo -e "${RED}Can't start ${ISO}!${RC}"
-	exit 1
+echo -ne "Verifying system requirements...${RC}"
+checkReq() {
+	for REQ in "${REQS[@]}"; do
+		if ! command -v "${REQ}">/dev/null;then
+			echo -e "To run me, you need:${WARN}${REQ}${RC}"
+			exit 1
+		fi
+	done
+}
+
+if checkReq	-wo 'vmx|svm' /proc/cpuinfo; then
+	echo -ne "${GOOD}[OK]\n${RC}"
+else
+	echo -ne "${WARN}[FALSE]\n${RC}"
 fi
+
+echo -ne "Computing available RAM...${RC}"
+if AVAIL_MEM=$(( $(grep -i MemAvail /proc/meminfo | awk '{print $2}') / 1024 )); then
+	echo -ne "${GOOD}[OK]${RC}\n"
+else
+	echo -ne "${WARN}[FALSE]${RC}\n"
+fi
+
+echo -ne "${GOOD}Starting VM...${RC}\n"
+qemu-system-x86_64 -boot d -cdrom "${ISO}" -m "${AVAIL_MEM}" || echo -e "${WARN}Can't start ${ISO}!${RC}"
